import { collection, addDoc } from "firebase/firestore";
import { db } from "../firebase/config";
import type { SurveyCategory } from "../types/survey";

interface SeedQuestion {
  category: SurveyCategory;
  text: { en: string; lv: string };
  options: { en: string; lv: string }[];
  /** Index of the correct answer (Knowledge category only) */
  correctIndex?: number;
}

const SAMPLE_QUESTIONS: SeedQuestion[] = [
  // ——— Section 1: Knowledge (K1–K20; K9 omitted – has two correct answers) ———

  // K1
  {
    category: "Knowledge",
    text: {
      en: "Which organization introduced the concept of the Sustainable Development Goals (SDGs)?",
      lv: "Kura organizācija ieviesa ilgtspējīgas attīstības mērķu (IAM) koncepciju?",
    },
    options: [
      { en: "World Health Organization (WHO)", lv: "Pasaules Veselības organizācija (PVO)" },
      { en: "United Nations (UN)", lv: "Apvienoto Nāciju Organizācija (ANO)" },
      { en: "International Monetary Fund (IMF)", lv: "Starptautiskais Valūtas fonds (SVF)" },
      { en: "World Trade Organization (WTO)", lv: "Pasaules Tirdzniecības organizācija (PTO)" },
    ],
    correctIndex: 1,
  },
  // K2
  {
    category: "Knowledge",
    text: {
      en: "Which three dimensions are typically included in sustainability?",
      lv: "Kādas trīs dimensijas parasti ietver ilgtspēja?",
    },
    options: [
      { en: "Environmental, cultural, and technological", lv: "Vides, kultūras un tehnoloģiskā" },
      { en: "Environmental, political, and economic", lv: "Vides, politiskā un ekonomiskā" },
      { en: "Economic, social, and environmental", lv: "Ekonomiskā, sociālā un vides" },
    ],
    correctIndex: 2,
  },
  // K3
  {
    category: "Knowledge",
    text: {
      en: "What does the term \"carpooling\" mean?",
      lv: "Ko nozīmē termins \"kopbraukšana\" (carpooling)?",
    },
    options: [
      { en: "Sharing a trip with others to reduce the number of vehicles on the road", lv: "Brauciena koplietošana ar citiem, lai samazinātu transportlīdzekļu skaitu uz ceļa" },
      { en: "Driving a car only during peak congestion hours", lv: "Braukšana ar automašīnu tikai sastrēgumstundu laikā" },
      { en: "Parking cars in groups to save space", lv: "Automašīnu novietošana grupās, lai ietaupītu vietu" },
      { en: "Renting a car for a short period of time", lv: "Automašīnas īre uz īsu laika periodu" },
    ],
    correctIndex: 0,
  },
  // K4
  {
    category: "Knowledge",
    text: {
      en: "Which of the following transport modes are not considered sustainable?",
      lv: "Kurš no šiem transporta veidiem netiek uzskatīts par ilgtspējīgu?",
    },
    options: [
      { en: "Walking", lv: "Iešana kājām" },
      { en: "Cycling", lv: "Riteņbraukšana" },
      { en: "Electric vehicles", lv: "Elektriskie transportlīdzekļi" },
      { en: "Diesel-powered vehicles", lv: "Dīzeļdzinēja transportlīdzekļi" },
      { en: "Public transport", lv: "Sabiedriskais transports" },
    ],
    correctIndex: 3,
  },
  // K5
  {
    category: "Knowledge",
    text: {
      en: "What does \"modal split\" mean in transport planning?",
      lv: "Ko nozīmē \"modālais sadalījums\" transporta plānošanā?",
    },
    options: [
      { en: "The number of highways or traffic lanes", lv: "Automaģistrāļu vai satiksmes joslu skaits" },
      { en: "The distribution of trips or passenger-kilometres among different transport modes", lv: "Braucienu vai pasažierkilometru sadalījums starp dažādiem transporta veidiem" },
      { en: "The number of parking spaces available in a city", lv: "Pilsētā pieejamo autostāvvietu skaits" },
      { en: "The share of hybrid vehicles in the vehicle fleet", lv: "Hibrīdtransportlīdzekļu īpatsvars transportlīdzekļu parkā" },
    ],
    correctIndex: 1,
  },
  // K6
  {
    category: "Knowledge",
    text: {
      en: "Approximately what share of global CO\u2082 emissions is generated by the transport sector?",
      lv: "Aptuveni kādu daļu no pasaules CO\u2082 emisijām rada transporta nozare?",
    },
    options: [
      { en: "10%", lv: "10%" },
      { en: "15%", lv: "15%" },
      { en: "25%", lv: "25%" },
      { en: "More than 50%", lv: "Vairāk nekā 50%" },
    ],
    correctIndex: 2,
  },
  // K7
  {
    category: "Knowledge",
    text: {
      en: "What is the main environmental advantage of public transport compared to private cars?",
      lv: "Kāda ir galvenā sabiedriskā transporta priekšrocība videi salīdzinājumā ar privātajām automašīnām?",
    },
    options: [
      { en: "Higher comfort level for passengers", lv: "Augstāks komforta līmenis pasažieriem" },
      { en: "Reduced travel time", lv: "Samazināts ceļā pavadītais laiks" },
      { en: "Lower energy consumption per passenger", lv: "Mazāks enerģijas patēriņš uz vienu pasažieri" },
      { en: "Higher fuel efficiency of private cars", lv: "Lielāka privāto automašīnu degvielas efektivitāte" },
    ],
    correctIndex: 2,
  },
  // K8
  {
    category: "Knowledge",
    text: {
      en: "What is the main goal of ensuring equity in transport systems?",
      lv: "Kāds ir galvenais mērķis, nodrošinot vienlīdzību transporta sistēmās?",
    },
    options: [
      { en: "Reducing travel time", lv: "Ceļā pavadītā laika samazināšana" },
      { en: "Ensuring equal access to safe and affordable mobility for all", lv: "Vienlīdzīgas piekļuves nodrošināšana drošai un pieejamas cenas mobilitātei visiem" },
      { en: "Increasing the number of electric vehicles on the roads", lv: "Elektrisko transportlīdzekļu skaita palielināšana uz ceļiem" },
      { en: "Prioritising car users in urban planning", lv: "Automašīnu lietotāju prioritizēšana pilsētplānošanā" },
    ],
    correctIndex: 1,
  },
  // K10 (K9 omitted – has two correct answers)
  {
    category: "Knowledge",
    text: {
      en: "Which transport mode usually produces the lowest emissions per passenger-kilometre in urban areas?",
      lv: "Kurš transporta veids parasti rada vismazākās emisijas uz pasažierkilometru pilsētvidē?",
    },
    options: [
      { en: "Walking", lv: "Iešana kājām" },
      { en: "Private petrol car", lv: "Privāta benzīna automašīna" },
      { en: "Motorcycle", lv: "Motocikls" },
      { en: "Taxi", lv: "Taksometrs" },
    ],
    correctIndex: 0,
  },
  // K11
  {
    category: "Knowledge",
    text: {
      en: "What is the main purpose of cycling infrastructure in cities?",
      lv: "Kāds ir galvenais riteņbraukšanas infrastruktūras mērķis pilsētās?",
    },
    options: [
      { en: "To increase car speeds", lv: "Palielināt automašīnu ātrumu" },
      { en: "To improve safety and encourage bicycle use", lv: "Uzlabot drošību un veicināt velosipēdu izmantošanu" },
      { en: "To reduce the number of buses", lv: "Samazināt autobusu skaitu" },
      { en: "To create more parking spaces", lv: "Izveidot vairāk autostāvvietu" },
    ],
    correctIndex: 1,
  },
  // K12
  {
    category: "Knowledge",
    text: {
      en: "What does the term \"active mobility\" usually refer to?",
      lv: "Ko parasti nozīmē termins \"aktīvā mobilitāte\"?",
    },
    options: [
      { en: "Travel using only electric vehicles", lv: "Pārvietošanās, izmantojot tikai elektriskos transportlīdzekļus" },
      { en: "Travel that involves physical activity, such as walking and cycling", lv: "Pārvietošanās, kas ietver fizisko aktivitāti, piemēram, iešanu kājām un riteņbraukšanu" },
      { en: "Travel by public transport only", lv: "Pārvietošanās tikai ar sabiedrisko transportu" },
      { en: "Travel for work purposes only", lv: "Pārvietošanās tikai darba vajadzībām" },
    ],
    correctIndex: 1,
  },
  // K13
  {
    category: "Knowledge",
    text: {
      en: "Why is reducing dependence on private cars important in cities?",
      lv: "Kāpēc ir svarīgi samazināt atkarību no privātajām automašīnām pilsētās?",
    },
    options: [
      { en: "It increases fuel sales", lv: "Tas palielina degvielas tirdzniecību" },
      { en: "It can reduce congestion, pollution, and land use for parking", lv: "Tas var samazināt sastrēgumus, piesārņojumu un zemes izmantošanu autostāvvietām" },
      { en: "It makes cities less accessible", lv: "Tas padara pilsētas mazāk pieejamas" },
      { en: "It reduces the need for sidewalks", lv: "Tas samazina nepieciešamību pēc ietvēm" },
    ],
    correctIndex: 1,
  },
  // K14
  {
    category: "Knowledge",
    text: {
      en: "Which of the following is an example of micromobility?",
      lv: "Kurš no šiem ir mikromobilitātes piemērs?",
    },
    options: [
      { en: "Intercity train", lv: "Starppilsētu vilciens" },
      { en: "Electric scooter", lv: "Elektriskais skrejritenis" },
      { en: "Airplane", lv: "Lidmašīna" },
      { en: "Diesel bus", lv: "Dīzeļa autobuss" },
    ],
    correctIndex: 1,
  },
  // K15
  {
    category: "Knowledge",
    text: {
      en: "What is one major benefit of trip chaining?",
      lv: "Kāds ir viens galvenais braucienu apvienošanas (trip chaining) ieguvums?",
    },
    options: [
      { en: "It increases the number of trips made", lv: "Tas palielina veikto braucienu skaitu" },
      { en: "It reduces the total distance or number of separate journeys", lv: "Tas samazina kopējo attālumu vai atsevišķu braucienu skaitu" },
      { en: "It makes public transport more expensive", lv: "Tas padara sabiedrisko transportu dārgāku" },
      { en: "It replaces the need for road maintenance", lv: "Tas aizstāj nepieciešamību pēc ceļu uzturēšanas" },
    ],
    correctIndex: 1,
  },
  // K16
  {
    category: "Knowledge",
    text: {
      en: "What is the main idea of transport accessibility?",
      lv: "Kāda ir galvenā transporta pieejamības ideja?",
    },
    options: [
      { en: "Making travel faster only for car users", lv: "Padarīt ceļošanu ātrāku tikai automašīnu lietotājiem" },
      { en: "Ensuring people can reach jobs, services, and education reasonably easily", lv: "Nodrošināt, ka cilvēki var samērā viegli nokļūt līdz darba vietām, pakalpojumiem un izglītībai" },
      { en: "Increasing the number of private vehicles", lv: "Palielināt privāto transportlīdzekļu skaitu" },
      { en: "Reducing ticket inspections", lv: "Samazināt biļešu pārbaudes" },
    ],
    correctIndex: 1,
  },
  // K17
  {
    category: "Knowledge",
    text: {
      en: "Which policy measure is commonly used to discourage excessive car use in city centres?",
      lv: "Kāds politikas pasākums parasti tiek izmantots, lai atturētu no pārmērīgas automašīnu lietošanas pilsētu centros?",
    },
    options: [
      { en: "Free fuel vouchers", lv: "Bezmaksas degvielas kuponi" },
      { en: "Congestion charging", lv: "Sastrēgumu maksa" },
      { en: "Removing sidewalks", lv: "Ietvju likvidēšana" },
      { en: "Reducing public transport frequency", lv: "Sabiedriskā transporta biežuma samazināšana" },
    ],
    correctIndex: 1,
  },
  // K18
  {
    category: "Knowledge",
    text: {
      en: "What is \"greenwashing\" in the context of transport?",
      lv: "Kas ir \"zaļmaldināšana\" (greenwashing) transporta kontekstā?",
    },
    options: [
      { en: "Repairing public roads using recycled materials", lv: "Publisko ceļu remonts, izmantojot pārstrādātus materiālus" },
      { en: "Presenting a transport solution as more environmentally friendly than it really is", lv: "Transporta risinājuma pasniegšana kā videi draudzīgāku, nekā tas patiesībā ir" },
      { en: "Switching from buses to trains", lv: "Pāreja no autobusiem uz vilcieniem" },
      { en: "Promoting cycling infrastructure", lv: "Riteņbraukšanas infrastruktūras veicināšana" },
    ],
    correctIndex: 1,
  },
  // K19
  {
    category: "Knowledge",
    text: {
      en: "Which of the following best describes a sustainable transport system?",
      lv: "Kurš no šiem vislabāk raksturo ilgtspējīgu transporta sistēmu?",
    },
    options: [
      { en: "A system focused mainly on increasing road capacity for cars", lv: "Sistēma, kas galvenokārt orientēta uz ceļu caurlaidspējas palielināšanu automašīnām" },
      { en: "A system that is safe, accessible, affordable, and environmentally responsible", lv: "Sistēma, kas ir droša, pieejama, par pieņemamu cenu un videi atbildīga" },
      { en: "A system with the highest possible speed limits", lv: "Sistēma ar visaugstākajiem iespējamajiem ātruma ierobežojumiem" },
      { en: "A system that prioritises air travel over all other modes", lv: "Sistēma, kas priekšroku dod gaisa transportam pār visiem citiem veidiem" },
    ],
    correctIndex: 1,
  },
  // K20
  {
    category: "Knowledge",
    text: {
      en: "Why are short car trips often especially inefficient from an environmental perspective?",
      lv: "Kāpēc īsi braucieni ar automašīnu bieži ir īpaši neefektīvi no vides viedokļa?",
    },
    options: [
      { en: "Because cars cannot be used for short trips", lv: "Jo automašīnas nevar izmantot īsiem braucieniem" },
      { en: "Because engines and vehicles often operate less efficiently on short trips", lv: "Jo dzinēji un transportlīdzekļi bieži darbojas mazāk efektīvi īsos braucienos" },
      { en: "Because short trips are illegal in some cities", lv: "Jo īsi braucieni dažās pilsētās ir nelikumīgi" },
      { en: "Because public transport is always unavailable for short trips", lv: "Jo sabiedriskais transports īsiem braucieniem vienmēr nav pieejams" },
    ],
    correctIndex: 1,
  },

  // ——— Section 2: Attitudes (A1–A10) ———
  // Scale: Strongly disagree (0) / Somewhat disagree (25) / Neutral (50) / Somewhat agree (75) / Strongly agree (100)
  // A3 is reworded to be forward-coded (higher agreement = more sustainable attitude).

  // A1
  {
    category: "Attitudes",
    text: {
      en: "I feel a personal responsibility to choose environmentally friendly modes of transport.",
      lv: "Es jūtu personīgu atbildību izvēlēties videi draudzīgus transporta veidus.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A2
  {
    category: "Attitudes",
    text: {
      en: "Using sustainable modes of transport (walking, cycling, public transport) is an important way to mitigate climate change.",
      lv: "Ilgtspējīgu transporta veidu (iešana kājām, riteņbraukšana, sabiedriskais transports) izmantošana ir svarīgs veids, kā mazināt klimata pārmaiņas.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A3 (originally reverse-coded; reworded to forward-coded)
  {
    category: "Attitudes",
    text: {
      en: "When choosing a mode of transport, I prioritise sustainability over convenience and comfort.",
      lv: "Izvēloties transporta veidu, es dodu priekšroku ilgtspējai, nevis ērtībai un komfortam.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A4
  {
    category: "Attitudes",
    text: {
      en: "Transport accessibility and equity \u2013 inclusive and accessible options for all \u2013 are essential components of a just society.",
      lv: "Transporta pieejamība un vienlīdzība \u2013 iekļaujoši un pieejami risinājumi visiem \u2013 ir taisnīgas sabiedrības būtiskas sastāvdaļas.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A5
  {
    category: "Attitudes",
    text: {
      en: "Government policy should actively limit excessive car use.",
      lv: "Valdības politikai būtu aktīvi jāierobežo pārmērīga automašīnu lietošana.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A6
  {
    category: "Attitudes",
    text: {
      en: "I support investments in walking and cycling infrastructure even if they reduce road space for private cars.",
      lv: "Es atbalstu ieguldījumus gājēju un riteņbraukšanas infrastruktūrā, pat ja tie samazina ceļa platību privātajām automašīnām.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A7
  {
    category: "Attitudes",
    text: {
      en: "Public transport should be prioritised in urban planning even when it requires public subsidies.",
      lv: "Sabiedriskajam transportam jābūt prioritāram pilsētplānošanā, pat ja tam nepieciešamas publiskās subsīdijas.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A8
  {
    category: "Attitudes",
    text: {
      en: "Choosing sustainable transport is easier when good infrastructure is available.",
      lv: "Ilgtspējīga transporta izvēli atvieglo laba infrastruktūras pieejamība.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A9
  {
    category: "Attitudes",
    text: {
      en: "Electric vehicles alone cannot solve all sustainability problems in transport.",
      lv: "Elektriskie transportlīdzekļi vieni paši nespēj atrisināt visas ilgtspējas problēmas transportā.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },
  // A10
  {
    category: "Attitudes",
    text: {
      en: "Transport policy should encourage people to reduce unnecessary travel by car.",
      lv: "Transporta politikai būtu jāmudina cilvēkus samazināt nevajadzīgus braucienus ar automašīnu.",
    },
    options: [
      { en: "Strongly disagree", lv: "Pilnībā nepiekrītu" },
      { en: "Somewhat disagree", lv: "Drīzāk nepiekrītu" },
      { en: "Neutral", lv: "Neitrāli" },
      { en: "Somewhat agree", lv: "Drīzāk piekrītu" },
      { en: "Strongly agree", lv: "Pilnībā piekrītu" },
    ],
  },

  // ——— Section 3: Behaviour (B1–B10) ———
  // Scale: Never (0) / Rarely (25) / Sometimes (50) / Often (75) / Always (100)

  // B1
  {
    category: "Behaviour",
    text: {
      en: "Whenever possible, I use public transport instead of driving a car.",
      lv: "Kad vien iespējams, es lietoju sabiedrisko transportu, nevis braucu ar automašīnu.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B2
  {
    category: "Behaviour",
    text: {
      en: "For short trips, I walk or cycle instead of using a car.",
      lv: "Īsiem braucieniem es eju kājām vai braucu ar riteni, nevis lietoju automašīnu.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B3
  {
    category: "Behaviour",
    text: {
      en: "I combine trips (trip chaining) to reduce the total number of journeys.",
      lv: "Es apvienoju braucienus (trip chaining), lai samazinātu kopējo braucienu skaitu.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B4
  {
    category: "Behaviour",
    text: {
      en: "I avoid flying or choose alternatives (e.g., train, bus) when available.",
      lv: "Es izvairos no lidošanas vai izvēlos alternatīvas (piemēram, vilciens, autobuss), kad tās ir pieejamas.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B5
  {
    category: "Behaviour",
    text: {
      en: "When thinking about everyday mobility, such as commuting to work, I try to choose sustainable modes of transport.",
      lv: "Domājot par ikdienas mobilitāti, piemēram, braucienu uz darbu, es cenšos izvēlēties ilgtspējīgus transporta veidus.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B6
  {
    category: "Behaviour",
    text: {
      en: "I choose walking when the destination is within a reasonable distance.",
      lv: "Es izvēlos iešanu kājām, ja galamērķis ir saprātīgā attālumā.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B7
  {
    category: "Behaviour",
    text: {
      en: "I use digital tools (journey planners, transport apps, shared mobility apps) to choose more sustainable travel options.",
      lv: "Es izmantoju digitālos rīkus (maršrutu plānotājus, transporta lietotnes, koplietošanas mobilitātes lietotnes), lai izvēlētos ilgtspējīgākus ceļošanas variantus.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B8
  {
    category: "Behaviour",
    text: {
      en: "I avoid unnecessary car use in city centres.",
      lv: "Es izvairos no nevajadzīgas automašīnu lietošanas pilsētas centros.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B9
  {
    category: "Behaviour",
    text: {
      en: "When possible, I share rides with others instead of travelling alone by car.",
      lv: "Kad iespējams, es dalos braucienos ar citiem, nevis braucu viens ar automašīnu.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },
  // B10
  {
    category: "Behaviour",
    text: {
      en: "I consider the environmental impact of transport when planning leisure trips.",
      lv: "Plānojot atpūtas braucienus, es ņemu vērā transporta ietekmi uz vidi.",
    },
    options: [
      { en: "Never", lv: "Nekad" },
      { en: "Rarely", lv: "Reti" },
      { en: "Sometimes", lv: "Dažreiz" },
      { en: "Often", lv: "Bieži" },
      { en: "Always", lv: "Vienmēr" },
    ],
  },

  // ——— Section 4: Confidence in One's Judgement (C1–C8) ———
  // Scale: Not confident (0) / Slightly confident (25) / Moderately confident (50) / Confident (75) / Very confident (100)

  // C1
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you in your knowledge about sustainable transport?",
      lv: "Cik pārliecināts(-a) esat par savām zināšanām par ilgtspējīgu transportu?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C2
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that your transport choices are sustainable?",
      lv: "Cik pārliecināts(-a) esat, ka jūsu transporta izvēles ir ilgtspējīgas?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C3
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you understand government transport policy, such as the Transport Development Guidelines 2021\u20132027?",
      lv: "Cik pārliecināts(-a) esat, ka izprotat valdības transporta politiku, piemēram, Transporta attīstības pamatnostādnes 2021.\u20132027. gadam?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C4
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you can recognise \"greenwashing\" in transport solutions?",
      lv: "Cik pārliecināts(-a) esat, ka spējat atpazīt \"zaļmaldināšanu\" (greenwashing) transporta risinājumos?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C5
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you can compare the sustainability of different transport modes?",
      lv: "Cik pārliecināts(-a) esat, ka spējat salīdzināt dažādu transporta veidu ilgtspēju?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C6
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you can identify misleading environmental claims in transport advertising?",
      lv: "Cik pārliecināts(-a) esat, ka spējat identificēt maldinošus vides apgalvojumus transporta reklāmā?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C7
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you understand how your personal travel choices affect emissions and sustainability?",
      lv: "Cik pārliecināts(-a) esat, ka izprotat, kā jūsu personīgās ceļošanas izvēles ietekmē emisijas un ilgtspēju?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
  // C8
  {
    category: "Confidence in One's Judgement",
    text: {
      en: "How confident are you that you know where to find reliable information about sustainable transport?",
      lv: "Cik pārliecināts(-a) esat, ka zināt, kur atrast ticamu informāciju par ilgtspējīgu transportu?",
    },
    options: [
      { en: "Not confident", lv: "Neesmu pārliecināts(-a)" },
      { en: "Slightly confident", lv: "Nedaudz pārliecināts(-a)" },
      { en: "Moderately confident", lv: "Mēreni pārliecināts(-a)" },
      { en: "Confident", lv: "Pārliecināts(-a)" },
      { en: "Very confident", lv: "Ļoti pārliecināts(-a)" },
    ],
  },
];


/**
 * Development-only utility: seeds the Firestore `questions` collection
 * with sample questions. Call from browser console:
 *
 *   import('/src/utils/seedQuestions.ts').then(m => m.seedSampleQuestions())
 */
export async function seedSampleQuestions(): Promise<void> {
  const ref = collection(db, "questions");
  let count = 0;
  for (const q of SAMPLE_QUESTIONS) {
    await addDoc(ref, q);
    count++;
  }
  console.log(`Seeded ${count} questions to Firestore.`);
}
